### ISSUE TITLE
Error #1

### ISSUE THREAD

**Issue by NotAShelf** [1stian/autorankup#2]
If the rankup checks are too frequent (2-3 minutes) and a player becomes eligible during that time, the plugin will throw errors and repeat the rankup commands on console.
![image](https://user-images.githubusercontent.com/62766066/85054274-7b52d380-b1a4-11ea-951e-3dc45cdb7756.png)

**Comment by 1stian** [comment]
Thank you for reporting. I will take a look at this! Will write back when I have a fix.
